### PR TITLE
#163318169 User Interface template to vote only one politician

### PR DESCRIPTION
**Pull request by perfect090**
*What does this PR do?*
Have User Interface template for voting only one politician

*Description of Task to be completed*
Have the following pages working and responsive
User sign up page
User sign in page
Voting page
Landing page
Profile page
Admin page

*Any background context you want to provide?*
This user interface template will only be made available during election time.  

*What are the relevant pivotal tracker stories?*
#163318169

### CODE REVIEW

**Comment by JCanaks** [comment]
@perfect090 Pls include screenshots on your PR. As described in the conventions. Also the heading should not be italicized follow the conventions pls
screen shot 2019-01-24 at 5 23 51 pm
The hashes help to bolden it
screen shot 2019-01-24 at 5 24 00 pm

**Comment by perfect090** [comment]
Okay...Noted. Thanks. By screenshots, are you referring to screenshots of any webpage built?                                                                                                                                                                                                                From: JCanaksSent: Thursday, January 24, 2019 17:24To: perfect090/PoliticoReply To: perfect090/PoliticoCc: perfect090; MentionSubject: Re: [perfect090/Politico] #163318169 User Interface template to vote only one politician (#7)@perfect090 Pls include screenshots on your PR. As described in the conventions. Also the heading should not be italicized follow the conventions pls

The hashes help to bolden it


—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/perfect090/Politico","title":"perfect090/Politico","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/perfect090/Politico"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JCanaks in #7: @perfect090 Pls include screenshots on your PR. As described in the conventions. Also the heading should not be italicized follow the conventions pls\r\n\u003cimg width=\"545\" alt=\"screen shot 2019-01-24 at 5 23 51 pm\" src=\"https://user-images.githubusercontent.com/26818808/51692281-df4b8980-1ffc-11e9-85d8-5b4af9f93375.png\"\u003e\r\nThe hashes help to bolden it\r\n\u003cimg width=\"555\" alt=\"screen shot 2019-01-24 at 5 24 00 pm\" src=\"https://user-images.githubusercontent.com/26818808/51692304-ebcfe200-1ffc-11e9-9206-7548ec35c9b2.png\"\u003e\r\n\r\n"}],"action":{"name":"View Pull Request","url":"https://github.com/perfect090/Politico/pull/7#issuecomment-457260260"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/perfect090/Politico/pull/7#issuecomment-457260260",
"url": "https://github.com/perfect090/Politico/pull/7#issuecomment-457260260",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by JCanaks** [comment]
@perfect090 Looks good. A few feedbacks:
screen shot 2019-01-24 at 5 34 49 pm
Capitalize the `V` in vote and make it more noticeable as I didn't notice it upon looking at your site. So you might want to change the color of the `vote` text  to the blue theme on the page and slighty increase the text font and radio button and then put a little more space between the `vote` text and the radio button.

**Comment by JCanaks** [comment]
screen shot 2019-01-24 at 5 35 00 pm
Please centralize your submit button

**Comment by JCanaks** [comment]
@perfect090 With regards to the screenshots for your PR. It is the screenshots of the page or feature you worked on

**Comment by perfect090** [comment]
Okay...Noted...I will make all the required changes a instructed...Thanks for the follow up                                                                                                                                                                                                                From: JCanaksSent: Thursday, January 24, 2019 17:46To: perfect090/PoliticoReply To: perfect090/PoliticoCc: perfect090; MentionSubject: Re: [perfect090/Politico] #163318169 User Interface template to vote only one politician (#7)@perfect090 With regards to the screenshots for your PR. It is the screenshots of the page or feature you worked on

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/perfect090/Politico","title":"perfect090/Politico","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/perfect090/Politico"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JCanaks in #7: @perfect090 With regards to the screenshots for your PR. It is the screenshots of the page or feature you worked on"}],"action":{"name":"View Pull Request","url":"https://github.com/perfect090/Politico/pull/7#issuecomment-457268415"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/perfect090/Politico/pull/7#issuecomment-457268415",
"url": "https://github.com/perfect090/Politico/pull/7#issuecomment-457268415",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Pull request merged**
