### PR TITLE
 #163318236 User profile page

### PR DESCRIPTION
**Pull request by perfect090**
*What does this PR do?*
Have User Interface template for profile page

*What are the relevant pivotal tracker stories?*
#163318236

### CODE REVIEW

**Comment by JCanaks** [comment]
Nice Work. A few feedbacks:
- The purple background and border used in your profile info does not go with the color theme of your app so choose a suitable color that blends in with the theme
- What is the concept behind the `following` and `followers`? and how does that fit in with the overall concept of Politico?
- The texts in the page are tiny you might what do increase (aside from the title headers)
- Combine the `offices you voted` and `candidates you voted` into one section with the heading `your votes` for example which displays both the candidates you voted alongside their corresponding office

Since you merge the authentication pages before feedback i will just put feedback for those here:
- In sign in page pls put a sign in header, centralize the form and increase the font size for the placeholder texts in the textfield
- In the signup pls centralize the `create an account header` it should be cntralized within the white box where the form is
- Increase the texts within the form fields and button for sign up as well

**Comment by perfect090** [comment]
Okay. Thank you very much. I will make changes to the feedbacks as instructed :)                                                                                                                                                                                                                From: JCanaksSent: Wednesday, January 23, 2019 17:54To: perfect090/PoliticoReply To: perfect090/PoliticoCc: perfect090; AuthorSubject: Re: [perfect090/Politico]  #163318236 User profile page (#3)Nice Work. A few feedbacks:

The purple background and border used in your profile info does not go with the color theme of your app so choose a suitable color that blends in with the theme
What is the concept behind the following and followers? and how does that fit in with the overall concept of Politico?
The texts in the page are tiny you might what do increase (aside from the title headers)
Combine the offices you voted and candidates you voted into one section with the heading your votes for example which displays both the candidates you voted alongside their corresponding office

Since you merge the authentication pages before feedback i will just put feedback for those here:

In sign in page pls put a sign in header, centralize the form and increase the font size for the placeholder texts in the textfield
In the signup pls centralize the create an account header it should be cntralized within the white box where the form is
Increase the texts within the form fields and button for sign up as well


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/perfect090/Politico","title":"perfect090/Politico","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/perfect090/Politico"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JCanaks in #3: Nice Work. A few feedbacks:\r\n- The purple background and border used in your profile info does not go with the color theme of your app so choose a suitable color that blends in with the theme\r\n- What is the concept behind the `following` and `followers`? and how does that fit in with the overall concept of Politico?\r\n- The texts in the page are tiny you might what do increase (aside from the title headers)\r\n- Combine the `offices you voted` and `candidates you voted` into one section with the heading `your votes` for example which displays both the candidates you voted alongside their corresponding office\r\n\r\nSince you merge the authentication pages before feedback i will just put feedback for those here:\r\n- In sign in page pls put a sign in header, centralize the form and increase the font size for the placeholder texts in the textfield\r\n- In the signup pls centralize the `create an account header` it should be cntralized within the white box where the form is\r\n- Increase the texts within the form fields and button for sign up as well\r\n"}],"action":{"name":"View Pull Request","url":"https://github.com/perfect090/Politico/pull/3#issuecomment-456879819"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/perfect090/Politico/pull/3#issuecomment-456879819",
"url": "https://github.com/perfect090/Politico/pull/3#issuecomment-456879819",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by JCanaks** [comment]
@perfect090 Additional feedback. Pls look for more appropriate pictures to use for your profile page that would boost it overall outlook

**Comment by perfect090** [comment]
Okay...Noted                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: JCanaksSent: Thursday, January 24, 2019 13:38To: perfect090/PoliticoReply To: perfect090/PoliticoCc: perfect090; MentionSubject: Re: [perfect090/Politico]  #163318236 User profile page (#3)@perfect090 Additional feedback. Pls look for more appropriate pictures to use for your profile page that would boost it overall outlook

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/perfect090/Politico","title":"perfect090/Politico","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/perfect090/Politico"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JCanaks in #3: @perfect090 Additional feedback. Pls look for more appropriate pictures to use for your profile page that would boost it overall outlook"}],"action":{"name":"View Pull Request","url":"https://github.com/perfect090/Politico/pull/3#issuecomment-457182263"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/perfect090/Politico/pull/3#issuecomment-457182263",
"url": "https://github.com/perfect090/Politico/pull/3#issuecomment-457182263",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Pull request merged**
