### PR TITLE
#163318117 User logged in and landing page.

### PR DESCRIPTION
**Pull request by perfect090**
*What does this PR do?*
Implements User Interface templates for logged in and landing page.

*What are the relevant pivotal tracker stories?*
#163318117

### CODE REVIEW

**Comment by perfect090** [comment]
Okay...Noted                                                                                                                                                                                                                From: JCanaksSent: Thursday, January 24, 2019 13:29To: perfect090/PoliticoReply To: perfect090/PoliticoCc: perfect090; MentionSubject: Re: [perfect090/Politico] #163318117 User logged in and landing page. (#4)@perfect090 pls follow the conventions for you PR descriptions as specified --> https://github.com/andela/workdey/wiki/PR-Format

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/perfect090/Politico","title":"perfect090/Politico","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/perfect090/Politico"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JCanaks in #4: @perfect090 pls follow the conventions for you PR descriptions as specified --\u003e https://github.com/andela/workdey/wiki/PR-Format \r\n"}],"action":{"name":"View Pull Request","url":"https://github.com/perfect090/Politico/pull/4#issuecomment-457179889"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/perfect090/Politico/pull/4#issuecomment-457179889",
"url": "https://github.com/perfect090/Politico/pull/4#issuecomment-457179889",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by JCanaks** [comment]
@perfect090 Great work
- For your landing page. I see that the color theme for our site is white, grey and blue so the green background is off so pls use something that follows the theme of your app.
- Also pls centralize the text and button and increase the font. This will make those elements catch the eyes of the user upon visiting the site
- For the logged in page the red and green text used in sentences like `Want to run for an office?` pls change it to something that goes with the overall theme of your site

**Comment by perfect090** [comment]
Okay. Noted. Thank you very much                                                                                                                                                                                                                 From: JCanaksSent: Thursday, January 24, 2019 13:50To: perfect090/PoliticoReply To: perfect090/PoliticoCc: perfect090; MentionSubject: Re: [perfect090/Politico] #163318117 User logged in and landing page. (#4)@perfect090 Great work

For your landing page. I see that the color theme for our site is white, grey and blue so the green background is off so pls use something that follows the theme of your app.
Also pls centralize the text and button and increase the font. This will make those elements catch the eyes of the user upon visiting the site
For the logged in page the red and green text used in sentences like Want to run for an office? pls change it to something that goes with the overall theme of your site


—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/perfect090/Politico","title":"perfect090/Politico","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/perfect090/Politico"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JCanaks in #4: @perfect090 Great work\r\n- For your landing page. I see that the color theme for our site is white, grey and blue so the green background is off so pls use something that follows the theme of your app.\r\n- Also pls centralize the text and button and increase the font. This will make those elements catch the eyes of the user upon visiting the site\r\n- For the logged in page the red and green text used in sentences like `Want to run for an office?` pls change it to something that goes with the overall theme of your site"}],"action":{"name":"View Pull Request","url":"https://github.com/perfect090/Politico/pull/4#issuecomment-457185301"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/perfect090/Politico/pull/4#issuecomment-457185301",
"url": "https://github.com/perfect090/Politico/pull/4#issuecomment-457185301",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by perfect090** [comment]
I will also implement the same thing for my parties page                                                                                                                                                                                                                From: King PerfectSent: Thursday, January 24, 2019 14:05To: JCanaksSubject: Re: [perfect090/Politico] #163318117 User logged in and landing page. (#4)                                                                                                                                                                                                                           Okay. Noted. Thank you very much                                                                                                                                                                                                                 From: JCanaksSent: Thursday, January 24, 2019 13:50To: perfect090/PoliticoReply To: perfect090/PoliticoCc: perfect090; MentionSubject: Re: [perfect090/Politico] #163318117 User logged in and landing page. (#4)@perfect090 Great work

For your landing page. I see that the color theme for our site is white, grey and blue so the green background is off so pls use something that follows the theme of your app.
Also pls centralize the text and button and increase the font. This will make those elements catch the eyes of the user upon visiting the site
For the logged in page the red and green text used in sentences like Want to run for an office? pls change it to something that goes with the overall theme of your site


—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/perfect090/Politico","title":"perfect090/Politico","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/perfect090/Politico"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JCanaks in #4: @perfect090 Great work\r\n- For your landing page. I see that the color theme for our site is white, grey and blue so the green background is off so pls use something that follows the theme of your app.\r\n- Also pls centralize the text and button and increase the font. This will make those elements catch the eyes of the user upon visiting the site\r\n- For the logged in page the red and green text used in sentences like `Want to run for an office?` pls change it to something that goes with the overall theme of your site"}],"action":{"name":"View Pull Request","url":"https://github.com/perfect090/Politico/pull/4#issuecomment-457185301"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/perfect090/Politico/pull/4#issuecomment-457185301",
"url": "https://github.com/perfect090/Politico/pull/4#issuecomment-457185301",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Pull request merged**
